project_name             = "twin"
environment              = "prod"
bedrock_model_id         = "amazon.nova-lite-v1:0"  # Use better model for production
lambda_timeout           = 60
api_throttle_burst_limit = 20
api_throttle_rate_limit  = 10
# We are currently using the CloudFront URL generated by Terraform.
# Set use_custom_domain = true and specify root_domain after purchasing
# and configuring a custom domain.
use_custom_domain        = false
root_domain              = ""
# For a custom domain use the following
# use_custom_domain        = true
# root_domain              = "yourdomain.com"  # Replace with your actual domain